// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhgceuwfwslqwkytgdoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZ2NldXdmd3NscXdreXRnZG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjA1MzAsImV4cCI6MjA3MTk5NjUzMH0.TD4keOwZiO_VzDqiBrtgZ5Gi2Q8050KyYgFxWYFnlT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});